version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .terraform
    - build

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  goconst:
    min-len: 2
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gocyclo:
    min-complexity: 15

  govet:
    shadow: true

  lll:
    line-length: 140

  misspell:
    locale: US

  revive:
    confidence: 0.8
    rules:
      - name: exported
        severity: error
      - name: unreachable-code
        severity: error
      - name: redefines-builtin-id
        severity: error

  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "Use go.uber.org/zap for logging instead"
        files:
          - "src/**/*.go"
          - "!**/*_test.go"

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-use-default: false
  exclude-rules:
    # Allow test files to be less strict
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - lll

    # Ignore certain govet reports that are acceptable
    - linters:
        - govet
      text: 'declaration of "(err|ctx)" shadows declaration at'

    # Ignore G404 (weak random) in test files
    - path: _test\.go
      text: "G404:"

    # Ignore line length in long URLs or import blocks
    - source: "https?://"
      linters:
        - lll
