run:
  timeout: 5m
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    exclude-functions:
      - "(*github.com/aws/aws-xray-sdk-go/xray.Segment).Close"
      - "(*github.com/aws/aws-xray-sdk-go/xray.Segment).AddAnnotation"
      - "(*github.com/aws/aws-xray-sdk-go/xray.Segment).AddMetadata"
      - "(*github.com/aws/aws-xray-sdk-go/xray.Segment).AddError"
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: lambda-go-template
  govet:
    shadow: true
  lll:
    line-length: 140
  misspell:
    locale: US
  revive:
    confidence: 0.8
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "Use go.uber.org/zap for logging instead"

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    # Allow test files to be less strict
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - gochecknoinits
    # Ignore "G404: Use of weak random number generator" in test files
    - path: _test\.go
      text: "G404:"
    # Ignore certain govet reports
    - linters:
        - govet
      text: 'declaration of "(err|ctx)" shadows declaration at'
    # Allow init functions in main.go files for logger setup
    - path: main\.go
      linters:
        - gochecknoinits
      text: "don't use `init` function"
    # Ignore errcheck for X-Ray operations that don't need error handling
    - source: "seg\\.Close\\(nil\\)"
      linters:
        - errcheck
    - source: "seg\\.AddAnnotation"
      linters:
        - errcheck
    - source: "seg\\.AddMetadata"
      linters:
        - errcheck
    - source: "seg\\.AddError"
      linters:
        - errcheck
